In [1]:
import numpy as np

In [2]:
a = [1, 2, 3]

In [3]:
b = [4]

In [4]:
def printSum(a,b):
    print(a+b)

In [5]:
printSum(a,b)

[1, 2, 3, 4]


In [6]:
a = np.array(a)

In [7]:
b = np.array(b)

In [8]:
printSum(a,b)

[5 6 7]


In [10]:
a = [[1,2,3],[1,2,3],[1,2,3]]
b = [4,6,7]

In [17]:
print(a,b)

[[1 2 3]
 [1 2 3]
 [1 2 3]] [4 6 7]


In [18]:
type(b)

numpy.ndarray

In [19]:
b = np.array(b)

In [14]:
a = np.array(a)

In [22]:
b = b.transpose().transpose()

In [23]:
printSum(a,b)

[[ 5  8 10]
 [ 5  8 10]
 [ 5  8 10]]


In [26]:
printSum(a.transpose(),b)

[[ 5  7  8]
 [ 6  8  9]
 [ 7  9 10]]
